# Generated by Django 4.0.3 on 2022-11-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_products_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='ref',
            field=models.CharField(default='9Uok8jQIkZZJHvu01Bm6Q2gKREFjkjMBV2rFpuvjlpgocVvUnVLAV9hYo-v9753rNXg<function uuid4 at 0x000001F3DEF5A3A0>', max_length=200, unique=True),
        ),
    ]
