# Generated by Django 4.0.3 on 2022-11-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_products_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=2083)),
                ('title', models.CharField(max_length=255)),
                ('describtion', models.CharField(max_length=2038)),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='ref',
            field=models.CharField(default='9-iN_oTXrz70SZHhyxc2I5RgBo50dW8VScmfohvjdFUp_4Q9d6FiIFIbr3Tk1XFds6Q<function uuid4 at 0x0000029DAF47A3A0>', max_length=200, unique=True),
        ),
    ]
