# Generated by Django 4.0.3 on 2022-11-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_home_url_alter_products_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='prodRef',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='ref',
            field=models.CharField(default='ri6DYLq40RSvVKkkCZP22r0lLZF-CMZhaedebEU0ncoiZBPhk07mSq02Wkc30eV9kTc<function uuid4 at 0x0000019660B7A3A0>', max_length=200, unique=True),
        ),
    ]
